### ISSUE TITLE
User input 

### ISSUE THREAD

**Issue by CristianSarac** [lewisjdeane/L-Dialogs#1]
hi there 
i like this library but i have a question 
is it possible to have the user enter or modify information in the dialog ? Lets say change the title ?

**Comment by lewisjdeane** [comment]
Yeah for sure, you mean like an edittext as the heading rather than textview?

**Comment by CristianSarac** [comment]
Yeah something like that 
To have edit texts instead of textviews

**Comment by lewisjdeane** [comment]
Okay I'll look into creating something like that for the next update.

**Comment by CristianSarac** [comment]
Super 
Looking forward

**Comment by lewisjdeane** [comment]
Okay this feature will actually work now that we have set up the ability to add custom views, will work in the next update.
