### ISSUE TITLE
Adding a custom View

### ISSUE THREAD

**Issue by 1baga** [lewisjdeane/L-Dialogs#10]
I tried adding a layout file to the method and it kept flagging an error... then i tried using the .seContentView() still it kept flagging an error... which makes me confused...by "customView" what do you actually mean?....

**Comment by 1baga** [comment]
sorry..solved the issue...i just inflated the layout and then used the .setCustomView()...

**Comment by ghost** [comment]
@1baga can you show some code snippets how you did it?

**Comment by 1baga** [comment]
@extraRam 

 public void startDialog(){
        CustomDialog.Builder builder = new CustomDialog.Builder(AddView.this, add_pres, positive);
        builder.darkTheme(false);
        builder.titleAlignment(BaseDialog.Alignment.CENTER);
        builder.titleColor("#e74c3c");
        builder.positiveColor("#e74c3c");
        CustomDialog cm = builder.build();
        View vm = getLayoutInflater().inflate(R.layout.pres_details, null);
        cm.setCustomView(vm);
        cm.show();
}
