### ISSUE TITLE
Can't reorder positive/negative text

### ISSUE THREAD

**Issue by easycheese** [lewisjdeane/L-Dialogs#14]
In your screenshots, the light example has the negative to the left of the positive and the dark example has one over the other.  How do you code it so the negative is to the left?  The default appears to be vertical but I can't find any options for horizontal.  I went through the code but can't find any options to use.

**Comment by lewisjdeane** [comment]
It automatically switches to stacked view when there is not enough space for side by side. Try reducing the length of string on both buttons

**Comment by easycheese** [comment]
Oh, the strings have to be seriously short.  Thanks

**Comment by lewisjdeane** [comment]
Yeah you can always reduce the text size of the buttons so you can fit more on the buttons with the latest update.
