### ISSUE TITLE
How to change ListDialogs selected color?

### ISSUE THREAD

**Issue by SingleCycleKing** [lewisjdeane/L-Dialogs#15]
Could you please tell me how to change the L-ListDialgs selected color?

**Comment by lewisjdeane** [comment]
I'm slightly confused as to the need of this, since when you click an item it dismisses it, could you elaborate it a bit more so I can understand exactly what you want it to do, cheers.

**Comment by ChrisMCMine** [comment]
@lewisjdeane I think he is talking about this: ![alt text](http://cyrilmottier.com/media/2011/08/listview-tips-tricks-3-create-fancy-listviews/list_selector_base.png)

@SingleCycleKing With the latest version of the L-Dialog you can do something like [here](http://stackoverflow.com/a/18572835/3593022):

``` java
StateListDrawable selector = new StateListDrawable();
selector.addState(new int[]{android.R.attr.state_pressed}, new ColorDrawable(R.color.color1));
selector.addState(new int[]{-android.R.attr.state_pressed}, new ColorDrawable(R.color.color2));

// The important part:
dialog.getListView().setSelector(selector);
```

**Comment by lewisjdeane** [comment]
Oh right I see, a selector, I'll add that later, cheers.

**Comment by SingleCycleKing** [comment]
Thank you, it's really a good work.
