### ISSUE TITLE
"Color" spelling

### ISSUE THREAD

**Issue by 3mph4515** [lewisjdeane/L-Dialogs#18]
I suppose, that renaming methods titleColor and itemColor to title/itemColour removes backward compatibility with old libs.

**Comment by StephaneBg** [comment]
We can do that:

```
    @Deprecated
    public Builder itemColourRes(int _colour) {
        return setItemColorRes(_colour);
    }

    public Builder setItemColorRes(int _color) {
        this.mItemColour = mContext.getResources().getColor(_color);
        return this;
    }
```

**Comment by lewisjdeane** [comment]
Sorry but I'm slightly confused by this issue, i've just renamed the methods to color rather than colour, switch to these for future usage.

**Comment by lewisjdeane** [comment]
I've changed the spelling of the methods than were colour to color, just use these methods instead for now.
