### ISSUE TITLE
Crash on init, please help

### ISSUE THREAD

**Issue by aldefy** [lewisjdeane/L-Dialogs#2]
08-18 13:23:15.023: E/AndroidRuntime(1508): FATAL EXCEPTION: main
08-18 13:23:15.023: E/AndroidRuntime(1508): Process: com.salut.jumbo, PID: 1508
08-18 13:23:15.023: E/AndroidRuntime(1508): android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.internal.widget.ActionBarView
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:814)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at uk.me.lewisdeane.ldialogs.CustomDialog.init(CustomDialog.java:55)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at uk.me.lewisdeane.ldialogs.CustomDialog.<init>(CustomDialog.java:48)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at some.package.SomeFragment$1.onClick(SomeFragment.java:27)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.View.performClick(View.java:4438)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.View$PerformClick.run(View.java:18422)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.os.Handler.handleCallback(Handler.java:733)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.os.Handler.dispatchMessage(Handler.java:95)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.os.Looper.loop(Looper.java:136)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.app.ActivityThread.main(ActivityThread.java:5017)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at java.lang.reflect.Method.invokeNative(Native Method)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at java.lang.reflect.Method.invoke(Method.java:515)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at dalvik.system.NativeStart.main(Native Method)
08-18 13:23:15.023: E/AndroidRuntime(1508): Caused by: java.lang.reflect.InvocationTargetException
08-18 13:23:15.023: E/AndroidRuntime(1508):     at java.lang.reflect.Constructor.constructNative(Native Method)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
08-18 13:23:15.023: E/AndroidRuntime(1508):     ... 22 more
08-18 13:23:15.023: E/AndroidRuntime(1508): Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class <unknown>
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.support.v7.internal.widget.ActionBarView.<init>(ActionBarView.java:218)
08-18 13:23:15.023: E/AndroidRuntime(1508):     ... 25 more
08-18 13:23:15.023: E/AndroidRuntime(1508): Caused by: java.lang.reflect.InvocationTargetException
08-18 13:23:15.023: E/AndroidRuntime(1508):     at java.lang.reflect.Constructor.constructNative(Native Method)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
08-18 13:23:15.023: E/AndroidRuntime(1508):     ... 32 more
08-18 13:23:15.023: E/AndroidRuntime(1508): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010012 a=-1}
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.content.res.Resources.loadDrawable(Resources.java:2068)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.widget.ImageView.<init>(ImageView.java:129)
08-18 13:23:15.023: E/AndroidRuntime(1508):     at android.widget.ImageView.<init>(ImageView.java:119)
08-18 13:23:15.023: E/AndroidRuntime(1508):     ... 35 more

**Comment by ChrisMCMine** [comment]
Have you added the support library? Looks like this is the reason for the crash

```
android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.internal.widget.ActionBarView
```

``` groovy
dependencies {
    compile 'com.android.support:appcompat-v7:1+'
}
```

**Comment by lewisjdeane** [comment]
Cheers for highlighting this, will take a look when I have time, I think Chris is probably right, just include the support library and it should work, but I'll still check it out regardless.

**Comment by aldefy** [comment]
yes i do have appcompat support lib added , and i am running an Eclipse IDE enviornment , project has no compile errors , and yes java folder is my source folder

**Comment by aldefy** [comment]
Reimported , readded support appcompat lib , moved and renamed fonts to assets/fonts/rlight.tff and all working now .

On a side note , a suggestion would be allow some sort of layout inflatable inside the content of the dialog to add some edittext and or some imageview , will prove to be useful
