### ISSUE TITLE
How to put buttons in line? {Question}

### ISSUE THREAD

**Issue by MenosGrante** [lewisjdeane/L-Dialogs#23]
Hello, I am using you library and it's greate. But i have question:
How can i put button in line, but not in column?

Now i have such result:
![screenshot_2014-09-08-19-51-14](https://cloud.githubusercontent.com/assets/2765109/4189045/6875148c-3778-11e4-8999-0da6addee2de.png)

**Comment by lewisjdeane** [comment]
It auto switches to stacked view if the text overflows on the buttons, make the text shorter or reduce button text size.
