### ISSUE TITLE
Light theme issue

### ISSUE THREAD

**Issue by Chirag-Galani** [lewisjdeane/L-Dialogs#26]
Hey mate,
This is an awesome library. But, I am unable to do so although i commented mDarkTheme, passed false value in it. 
Since, I am using eclipse had to copy your src files, style and other values in my project. All worked good except this Light theme issue. :(
Thanks for this lib. :) :+1:

**Comment by StephaneBg** [comment]
There is a bug in the CustomListDialog constructor. Call to super should be:

// Call super class constructor to create our dialog.
super(new ContextThemeWrapper(_builder.mContext, _builder.mIsDark ? R.style.Dark : R.style.Light));

**Comment by lewisjdeane** [comment]
Ah yes, my apologies will be updated when I get home, sorry about this.
