### ISSUE TITLE
Problem at setCustomView()

### ISSUE THREAD

**Issue by mthli** [lewisjdeane/L-Dialogs#33]
`setCustomView()` is good, but when I use it, I found a problem.

When I try to add a `WebView` at a L-Dialogs, you know that some web pages are long so they compress the Confirm Button and the Cancel Buttom under the screen, we can't see them. 

Meanwhile, the AlertDialog doesn't have this problem, we can still get the Button.

**Comment by ChrisMCMine** [comment]
#40 should fix this
