### ISSUE TITLE
Long text cannot be showed

### ISSUE THREAD

**Issue by franshua91** [lewisjdeane/L-Dialogs#36]
My content text is very long and it does not have a scroller in order to see all the text.

Thanks

**Comment by prashantwosti** [comment]
yes, I too need a scrollable content text.

**Comment by lewisjdeane** [comment]
Use setCustomView method with a ScrollView and it will work, I will default it to a ScollView soon however.

**Comment by prashantwosti** [comment]
Normal users would like to see a workaround example for setCustomView with CustomDialog.

Thanks

**Comment by ChrisMCMine** [comment]
#40 fixes this by wrapping everything inside a ScrollView
