### ISSUE TITLE
Stacked full-width buttons

### ISSUE THREAD

**Issue by ChrisMCMine** [lewisjdeane/L-Dialogs#4]
When text labels exceed the maximum button width, stacked buttons should be used.

[![alt-text](http://material-design.storage.googleapis.com/images/components-dialogs-usage-stackedfullwidthbuttonsa_large_mdpi.png)](http://www.google.com/design/spec/components/dialogs.html)

**Comment by lewisjdeane** [comment]
Okay cool will look into adding this for the next release, thanks.

**Comment by lewisjdeane** [comment]
Okay, I've added this feature in the latest commits. It will auto switch to the stacked view when the text overflows. 
![dfg_2014-08-27-23-25-11](https://cloud.githubusercontent.com/assets/6597449/4069077/3b9398ee-2e40-11e4-80ed-71945f74f0eb.png)
