### ISSUE TITLE
Custom Views as content (req)

### ISSUE THREAD

**Issue by gijsdewit** [lewisjdeane/L-Dialogs#5]
Hey, first of all, great lib. 
I was wondering if it's possible to add custom views to the dialog. I would really like to add images to the dialog. One way of doing that with the default dialogs in Android was to use setView() and set an ImageView, so maybe you can do something similar.  

Thanks.

**Comment by ChrisMCMine** [comment]
That's not possible at the moment

**Comment by aldefy** [comment]
I have done some experiment , my results are : 

![device-2014-08-22-160226](https://cloud.githubusercontent.com/assets/1392571/4009701/2e454ff4-29e8-11e4-80bb-cb27f1d7e649.png)
![device-2014-08-22-160236](https://cloud.githubusercontent.com/assets/1392571/4009702/330f02d2-29e8-11e4-8a70-2bb3aff09101.png)

![device-2014-08-22-160517](https://cloud.githubusercontent.com/assets/1392571/4009711/4ba08078-29e8-11e4-867e-773429348b97.png)

![device-2014-08-22-160838](https://cloud.githubusercontent.com/assets/1392571/4009723/863fd17a-29e8-11e4-9309-baf97c22fa06.png)

![device-2014-08-22-160532](https://cloud.githubusercontent.com/assets/1392571/4009714/4ef0e376-29e8-11e4-96b0-43f2bb214eee.png)

**Comment by aldefy** [comment]
Imageview too :  
![device-2014-08-22-162643](https://cloud.githubusercontent.com/assets/1392571/4009879/1617349e-29eb-11e4-9173-86ff424ecc7c.png)

**Comment by ChrisMCMine** [comment]
Made a Pull Request: 020692a976bde2975be8a9cad1565584af2bad7f

**Comment by lewisjdeane** [comment]
This looks good, I'll play around with it soon, got lots of other projects ongoing at the moment but I'll try merge it soon!

**Comment by lewisjdeane** [comment]
Okay, I've merged the commits, I'll do some further testing to check it works in a broader range of scenarios, thanks everyone for helping with this issue, I don't think I could've managed it myself.
