### ISSUE TITLE
Click events

### ISSUE THREAD

**Issue by ghost** [lewisjdeane/L-Dialogs#6]
I'm new to this so how exactly to handle click events for CustomDialogs. I have 3 dialogs and if I implement CustomDialog.ClickListener and then onConfirmClick() & onCancelClick(), all confirm and cancel buttons from all dialogs use the same method & functionality..

**Comment by ghost** [comment]
Nevermind, I found a workaround.  onConfirmClick() && onCancelClick() before doing stuff, check if the dialog isn't null and it's visible. Do this for all dialogs and it will work perfectly.

``` java

public void onConfirmClick(){
        if(customDialog !=null && customDialog.isShowing()){
                 //Do stuff...
        }
}
```

**Comment by lewisjdeane** [comment]
Just use the built in method .setClickListener(new CustomDialog.ClickListener(){....}); as mentioned in the read me.
