### ISSUE TITLE
Dismiss when tapped outside of dialog.

### ISSUE THREAD

**Issue by aercanozcan** [lewisjdeane/L-Dialogs#8]
This needs to be implemented to achieve default behavior of an android dialog in my humble opinion. I would like to contribute if necessary.

**Comment by lewisjdeane** [comment]
What do you mean? It does dismiss when you click outside?

**Comment by aercanozcan** [comment]
I mean it should dismiss when i tap outside of dialog. It is just a suggestion of course.

**Comment by lewisjdeane** [comment]
It does already though, I haven't modified that.

**Comment by ghost** [comment]
I think he means that you shouldn't have to set an onCancelListener for it to dismiss. I too have experienced the same thing where if I don't define an onCancelListener, I cannot dismiss the dialog when tapped outside. 

@aercanozcan you might try defining an onCancelListener for it to work.

**Comment by lewisjdeane** [comment]
Oh right, I'll take a look at it, thanks for bringing this to my attention.

**Comment by aercanozcan** [comment]
@AMQTech  oh. I didn't know that. Thanks.

**Comment by lewisjdeane** [comment]
Still unsure as to what the issue is, the dialog always dismisses for me and when clicked either outside the dialog or on either button, and also tested with and without a click listener

**Comment by lewisjdeane** [comment]
Okay as far as I'm concerned this issue is closed, thanks.
